/*
 * EU-SEC CA API
 * This is audit-api serves evidences for a continuous audit. In the EU-Sec project such evidences are collected and evaluated to determine the compliance status based on controls from the    [ccm](https://cloudsecurityalliance.org/group/cloud-controls-matrix).
 *
 * OpenAPI spec version: 1.0.5
 * Contact: contact@sec-cert.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package eu.sec.cert.api;

import eu.sec.cert.ApiException;
import eu.sec.cert.model.ScopeResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CaApiScopeApi
 */
@Ignore
public class CaApiScopeApiTest {

    private final CaApiScopeApi api = new CaApiScopeApi();

    
    /**
     * Returns all scopes of the cloud service
     *
     * Returns the available scopes for the cloud service. The scope corresponds often with the layers of the cloud service architecture like IaaS, PaaS, SaaS.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getScopesTest() throws ApiException {
        ScopeResponse response = api.getScopes();

        // TODO: test validations
    }
    
}
