/*
 * EU-SEC CA API
 * This is audit-api serves evidences for a continuous audit. In the EU-Sec project such evidences are collected and evaluated to determine the compliance status based on controls from the    [ccm](https://cloudsecurityalliance.org/group/cloud-controls-matrix).
 *
 * OpenAPI spec version: 1.0.8
 * Contact: contact@sec-cert.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package eu.sec.cert.api;

import eu.sec.cert.ApiException;
import eu.sec.cert.model.ObjectResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CaApiObjectsApi
 */
@Ignore
public class CaApiObjectsApiTest {

    private final CaApiObjectsApi api = new CaApiObjectsApi();

    
    /**
     * Returns Object ids of all objects that are in the scope of the audit.
     *
     * Returns the auditable object ids that are subject to the audit. The results can be limited according to a time range.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getObjectsTest() throws ApiException {
        String scope = null;
        String from = null;
        String to = null;
        Integer limit = null;
        ObjectResponse response = api.getObjects(scope, from, to, limit);

        // TODO: test validations
    }
    
}
