/*
 * EU-SEC CA API
 * This is audit-api serves evidences for a continuous audit. In the EU-Sec project such evidences are collected and evaluated to determine the compliance status based on controls from the    [ccm](https://cloudsecurityalliance.org/group/cloud-controls-matrix).
 *
 * OpenAPI spec version: 1.0.5
 * Contact: contact@sec-cert.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package eu.sec.cert.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import eu.sec.cert.model.LocationStorageResponseStorages;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * LocationStorageResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-16T13:44:30.652+02:00")
public class LocationStorageResponse {
  @SerializedName("storages")
  private List<LocationStorageResponseStorages> storages = new ArrayList<LocationStorageResponseStorages>();

  public LocationStorageResponse storages(List<LocationStorageResponseStorages> storages) {
    this.storages = storages;
    return this;
  }

  public LocationStorageResponse addStoragesItem(LocationStorageResponseStorages storagesItem) {
    this.storages.add(storagesItem);
    return this;
  }

   /**
   * Get storages
   * @return storages
  **/
  @ApiModelProperty(example = "[{\"uri\":\"i-0434c5582f2853d0c\",\"type\":\"service\",\"description\":\"AWS EC2 insctance\"},{\"uri\":\"vol-04b6088c76eb68a73\",\"type\":\"service\",\"description\":\"AWS EBS instance\"},{\"uri\":\"jdbc:mysql://192.168.0.10/SuperDB\",\"type\":\"database\"}]", required = true, value = "")
  public List<LocationStorageResponseStorages> getStorages() {
    return storages;
  }

  public void setStorages(List<LocationStorageResponseStorages> storages) {
    this.storages = storages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocationStorageResponse locationStorageResponse = (LocationStorageResponse) o;
    return Objects.equals(this.storages, locationStorageResponse.storages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(storages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocationStorageResponse {\n");
    
    sb.append("    storages: ").append(toIndentedString(storages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

