/*
 * EU-SEC CA API
 * This is audit-api serves evidences for a continuous audit. In the EU-Sec project such evidences are collected and evaluated to determine the compliance status based on controls from the    [ccm](https://cloudsecurityalliance.org/group/cloud-controls-matrix).
 *
 * OpenAPI spec version: 1.0.5
 * Contact: contact@sec-cert.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package eu.sec.cert.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import eu.sec.cert.model.ObjectResponseObjects;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ObjectResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-16T13:44:30.652+02:00")
public class ObjectResponse {
  @SerializedName("objects")
  private List<ObjectResponseObjects> objects = null;

  public ObjectResponse objects(List<ObjectResponseObjects> objects) {
    this.objects = objects;
    return this;
  }

  public ObjectResponse addObjectsItem(ObjectResponseObjects objectsItem) {
    if (this.objects == null) {
      this.objects = new ArrayList<ObjectResponseObjects>();
    }
    this.objects.add(objectsItem);
    return this;
  }

   /**
   * Get objects
   * @return objects
  **/
  @ApiModelProperty(example = "[{\"id\":\"m121\",\"type\":\"message\"},{\"id\":\"f6\",\"type\":\"file\"},{\"id\":\"COO.200.200.2.244\",\"type\":\"file\"}]", value = "")
  public List<ObjectResponseObjects> getObjects() {
    return objects;
  }

  public void setObjects(List<ObjectResponseObjects> objects) {
    this.objects = objects;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjectResponse objectResponse = (ObjectResponse) o;
    return Objects.equals(this.objects, objectResponse.objects);
  }

  @Override
  public int hashCode() {
    return Objects.hash(objects);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjectResponse {\n");
    
    sb.append("    objects: ").append(toIndentedString(objects)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

