/*
 * EU-SEC CA API
 * This is audit-api serves evidences for a continuous audit. In the EU-Sec project such evidences are collected and evaluated to determine the compliance status based on controls from the    [ccm](https://cloudsecurityalliance.org/group/cloud-controls-matrix).
 *
 * OpenAPI spec version: 1.0.7
 * Contact: contact@sec-cert.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package eu.sec.cert.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PasswordRequirementsResponsePasswordRequirements
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-11T14:46:49.847+01:00")
public class PasswordRequirementsResponsePasswordRequirements {
  @SerializedName("minimalLength")
  private Integer minimalLength = null;

  @SerializedName("upperAndLowerCaseEnforcement")
  private Boolean upperAndLowerCaseEnforcement = null;

  @SerializedName("numericCharacterEnforcement")
  private Boolean numericCharacterEnforcement = null;

  @SerializedName("specialCharacterEnforcement")
  private Boolean specialCharacterEnforcement = null;

  public PasswordRequirementsResponsePasswordRequirements minimalLength(Integer minimalLength) {
    this.minimalLength = minimalLength;
    return this;
  }

   /**
   * Get minimalLength
   * @return minimalLength
  **/
  @ApiModelProperty(example = "10", value = "")
  public Integer getMinimalLength() {
    return minimalLength;
  }

  public void setMinimalLength(Integer minimalLength) {
    this.minimalLength = minimalLength;
  }

  public PasswordRequirementsResponsePasswordRequirements upperAndLowerCaseEnforcement(Boolean upperAndLowerCaseEnforcement) {
    this.upperAndLowerCaseEnforcement = upperAndLowerCaseEnforcement;
    return this;
  }

   /**
   * Get upperAndLowerCaseEnforcement
   * @return upperAndLowerCaseEnforcement
  **/
  @ApiModelProperty(value = "")
  public Boolean isUpperAndLowerCaseEnforcement() {
    return upperAndLowerCaseEnforcement;
  }

  public void setUpperAndLowerCaseEnforcement(Boolean upperAndLowerCaseEnforcement) {
    this.upperAndLowerCaseEnforcement = upperAndLowerCaseEnforcement;
  }

  public PasswordRequirementsResponsePasswordRequirements numericCharacterEnforcement(Boolean numericCharacterEnforcement) {
    this.numericCharacterEnforcement = numericCharacterEnforcement;
    return this;
  }

   /**
   * Get numericCharacterEnforcement
   * @return numericCharacterEnforcement
  **/
  @ApiModelProperty(value = "")
  public Boolean isNumericCharacterEnforcement() {
    return numericCharacterEnforcement;
  }

  public void setNumericCharacterEnforcement(Boolean numericCharacterEnforcement) {
    this.numericCharacterEnforcement = numericCharacterEnforcement;
  }

  public PasswordRequirementsResponsePasswordRequirements specialCharacterEnforcement(Boolean specialCharacterEnforcement) {
    this.specialCharacterEnforcement = specialCharacterEnforcement;
    return this;
  }

   /**
   * Get specialCharacterEnforcement
   * @return specialCharacterEnforcement
  **/
  @ApiModelProperty(value = "")
  public Boolean isSpecialCharacterEnforcement() {
    return specialCharacterEnforcement;
  }

  public void setSpecialCharacterEnforcement(Boolean specialCharacterEnforcement) {
    this.specialCharacterEnforcement = specialCharacterEnforcement;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PasswordRequirementsResponsePasswordRequirements passwordRequirementsResponsePasswordRequirements = (PasswordRequirementsResponsePasswordRequirements) o;
    return Objects.equals(this.minimalLength, passwordRequirementsResponsePasswordRequirements.minimalLength) &&
        Objects.equals(this.upperAndLowerCaseEnforcement, passwordRequirementsResponsePasswordRequirements.upperAndLowerCaseEnforcement) &&
        Objects.equals(this.numericCharacterEnforcement, passwordRequirementsResponsePasswordRequirements.numericCharacterEnforcement) &&
        Objects.equals(this.specialCharacterEnforcement, passwordRequirementsResponsePasswordRequirements.specialCharacterEnforcement);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minimalLength, upperAndLowerCaseEnforcement, numericCharacterEnforcement, specialCharacterEnforcement);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PasswordRequirementsResponsePasswordRequirements {\n");
    
    sb.append("    minimalLength: ").append(toIndentedString(minimalLength)).append("\n");
    sb.append("    upperAndLowerCaseEnforcement: ").append(toIndentedString(upperAndLowerCaseEnforcement)).append("\n");
    sb.append("    numericCharacterEnforcement: ").append(toIndentedString(numericCharacterEnforcement)).append("\n");
    sb.append("    specialCharacterEnforcement: ").append(toIndentedString(specialCharacterEnforcement)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

