/*
 * EU-SEC CA API
 * This is audit-api serves evidences for a continuous audit. In the EU-Sec project such evidences are collected and evaluated to determine the compliance status based on controls from the    [ccm](https://cloudsecurityalliance.org/group/cloud-controls-matrix).
 *
 * OpenAPI spec version: 1.0.7
 * Contact: contact@sec-cert.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package eu.sec.cert.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SubmittedResponseItems
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-11T14:46:49.847+01:00")
public class SubmittedResponseItems {
  @SerializedName("uri")
  private String uri = null;

  @SerializedName("endpoint")
  private String endpoint = null;

  @SerializedName("timeSubmitted")
  private String timeSubmitted = null;

  public SubmittedResponseItems uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Get uri
   * @return uri
  **/
  @ApiModelProperty(example = "nextcloud.log", value = "")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public SubmittedResponseItems endpoint(String endpoint) {
    this.endpoint = endpoint;
    return this;
  }

   /**
   * Get endpoint
   * @return endpoint
  **/
  @ApiModelProperty(example = "https://endpoint:8080?push", value = "")
  public String getEndpoint() {
    return endpoint;
  }

  public void setEndpoint(String endpoint) {
    this.endpoint = endpoint;
  }

  public SubmittedResponseItems timeSubmitted(String timeSubmitted) {
    this.timeSubmitted = timeSubmitted;
    return this;
  }

   /**
   * to date in ISO-8601 format
   * @return timeSubmitted
  **/
  @ApiModelProperty(example = "2005-08-15T15:52:01+0000", value = "to date in ISO-8601 format")
  public String getTimeSubmitted() {
    return timeSubmitted;
  }

  public void setTimeSubmitted(String timeSubmitted) {
    this.timeSubmitted = timeSubmitted;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubmittedResponseItems submittedResponseItems = (SubmittedResponseItems) o;
    return Objects.equals(this.uri, submittedResponseItems.uri) &&
        Objects.equals(this.endpoint, submittedResponseItems.endpoint) &&
        Objects.equals(this.timeSubmitted, submittedResponseItems.timeSubmitted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uri, endpoint, timeSubmitted);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubmittedResponseItems {\n");
    
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    endpoint: ").append(toIndentedString(endpoint)).append("\n");
    sb.append("    timeSubmitted: ").append(toIndentedString(timeSubmitted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

